DefaultContentLanguage = "de"
languageCode = "de-de"
title = "mathias wellner"
baseurl = "https://mwellner.de/"
theme = "hugo-theme-bootstrap4-blog"
googleAnalytics = "UA-3650294-2"

[permalinks]
  post = "/:year/:month/:title/"
  page = "/:slug/"

[params]
  author = "Mathias Wellner"
  date_format = "15.01.2006"

[Languages]
[Languages.en]
[Languages.de]
