DefaultContentLanguage = "de"
languageCode = "de-de"
title = "mathias wellner"
baseurl = "https://mwellner.de/"
theme = "hugo-theme-bootstrap4-blog"
googleAnalytics = "UA-3650294-2"
enableRobotsTXT = true
paginate = 10

[permalinks]
  post = "/:year/:month/:day/:title/"
  page = "/:slug/"

[params]
  author = "Mathias Wellner"
  date_format = "02.01.2006"

[params.sidebar]
  num_recent_posts = 6

[Languages]
[Languages.de]
[Languages.en]
