DefaultContentLanguage = "de"
languageCode = "de-de"
title = "Mathias Wellner"
baseurl = "https://mwellner.de/"
theme = "hugo-theme-bootstrap4-blog"
enableRobotsTXT = true
paginate = 10
rssLimit = 20

[permalinks]
  post = "/:year/:month/:day/:slug/"
  page = "/:slug/"

[params]
  author = "Mathias Wellner"
  date_format = "02.01.2006"

[Languages]
[Languages.de]
[Languages.en]
